# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-dynamodb-cognito-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
        - s3:GetObject
        - s3:PutObject
      Resource: "*"

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  userPoolName: test-user-pool-${self:custom.currentStage}
  userPoolClientName: test-user-pool-client-${self:custom.currentStage}
package:
  individually: true
functions:
  
  hello:
    handler: handler.handler
    events:
      - http:
          path: /getAllDeviceReadings
          method: get
          cors: true
          # authorizer:
          #   type: COGNITO_USER_POOLS
          #   authorizerId:
          #     Ref: ApiGatewayAuthorizer
      - http:
          path: /{proxy+}
          method: any
          cors: true
          # authorizer:
          #   type: COGNITO_USER_POOLS
          #   authorizerId:
          #     Ref: ApiGatewayAuthorizer
  # graphql:
  #   description: GraphQL api
  #   handler: functions/graphql/graphql.graphQlQuery
  #   memorySize: 512
  #   events:
  #     - http:
  #         path: graphql
  #         method: post
  #         cors: 
  #            origin: '*'
  # dataFunction:
  #   handler: functions/daily.handler
  #   description: dynamoDB functions 
  #   timeout: 60
  # grahplQuery:
  #   description: GraphQL api query
  #   handler: api/graphql.query
  #   memorySize: 512
  #   events:
  #     - http:
  #         path: query
  #         method: post
  #         cors: true
resources:
  Description: Monitoreo Continuo de los dispositivos
  Resources:
    dataSheetReadings:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "devicetable-datasheet-readings"
    ###
    # Tabla de las lecturas del dispositivo.
    ###
    deviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "deviceTable"
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    deviceConfiguration:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "deviceConfiguration"
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    relaysConfiguration:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "relaysConfiguration"
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DeviceConnection: 
      Type:  AWS::DynamoDB::Table
      Properties:
        TableName: "DeviceConnection"
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5 
    fareConfiguration: 
      Type:  AWS::DynamoDB::Table
      Properties:
        TableName: "fareConfiguration"
        AttributeDefinitions:
          - AttributeName: fareConfigurationId
            AttributeType: S
        KeySchema:
          - AttributeName: fareConfigurationId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5 
    deviceReadings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "deviceReadings"
        AttributeDefinitions:
          - AttributeName: "primarykey"
            AttributeType: S
          - AttributeName: "sortkey"
            AttributeType: N
        KeySchema:
          - AttributeName: "primarykey"
            KeyType: HASH
          - AttributeName: "sortkey"
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
    iotRule:
      Type: AWS::IoT::TopicRule
      Properties:
        TopicRulePayload:
          Actions:
            - 
              DynamoDBv2:
                PutItem:
                  TableName: "deviceReadings"
                RoleArn: !GetAtt [iotRuleAllowDynamoWrites, Arn]
          AwsIotSqlVersion: "2016-03-23"
          Description: "Forwards incoming sensor messages to DynamoDB for analysis"
          RuleDisabled: false
          Sql: >-
            SELECT *, 
                  'ArduinoDevice01' as primarykey, 
                  (timestamp() / 1000) as sortkey,
                  ((timestamp() / 1000) + 2592000) as ttl
                  from 'deviceReadings'   
    iotPolicyForDevices:
      Type: AWS::IoT::Policy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "iot:Connect"
              Resource: "*"
              Condition:
                Bool:
                  "iot:Connection.Thing.IsAttached": [true]
            -
              Effect: "Allow"
              Action:
                - "iot:Publish"
              Resource: 
                - Fn::Join:
                   - ""
                   - - "arn:aws:iot:"
                     - Ref: AWS::Region
                     - ":"
                     - Ref: AWS::AccountId
                     - ":topic/$aws/rules/"
                     - Ref: iotRule
    ### 
    # Rol para el topico de la rol
    ####
    iotRuleAllowDynamoWrites:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "iot.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Path: "/"
        Policies:
          -
            PolicyName: "Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement: 
                - Effect: "Allow"
                  Action:
                    - "dynamodb:PutItem"
                  Resource: !GetAtt [deviceReadings, Arn]
        # cognito user pool
        ##
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        MfaConfiguration: OFF
        UserPoolName: ${self:custom.userPoolName}
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: True
            RequireNumbers: True
            RequireSymbols: True
            RequireUppercase: True
        Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: false
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: false
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: false
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: ${self:custom.userPoolClientName}
        GenerateSecret: False
        UserPoolId:
          Ref: CognitoUserPool
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]
  Outputs:
    CognitoUserPoolArn:
      Value:
        Fn::GetAtt:
          - CognitoUserPool
          - Arn
      Export:
        Name: CognitoUserPoolArn-${self:custom.currentStage}       

